### ISSUE TITLE
Changes to behavior of SQL output pane

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql-vscode#157]
I'm using the 0.6.1 version of the VS Code extension. If I open a PRQL query from a file, then hit Cmd-Shift-P to open the PRQL Extension, the right half of the window fills with the generated SQL as expected.

But if I open another PRQL query file in the left half, the SQL in the right side does not change.

My impression is that this is different from previous versions, where changing the PRQL query displayed changes the SQL Output window. Or am I simply mistaken... Thanks.

**Comment by max-sixty** [comment]
Yes, this seems to happen — the preview is now linked to a specific file rather than being generic for whichever file was last open.

Without understanding all the tradeoffs, I marginally preferred the old approach (i.e. possibly there are other things this approach enables).

One other thing I see — with two files open, each with previews available, when switching between PRQL files, the focus is grabbed by the preview. Ideally the preview would never grab focus (there's not much we can do with it...)

**Comment by richb-hanover** [comment]
I wanted to follow up on my initial report. After playing with it more, I finally realized that the 0.6.1 version is designed to make it easier to preserve the SQL results from the PRQL query. 

I strongly prefer the prior (0.6.0?) behavior. In my workflow, I like to treat the PRQL query files as the sole "source of truth". I don't find a need to keep the SQL results. They're just interim data that I copy/paste into my database. 

Here are the features that I appreciate/treasure from the extension, and how I'd like to operate again:

* The SQL Preview Pane simply displays the current PRQL file.
   * When I open the SQL Preview Pane, it displays the results of the current PRQL file open on the left.
   * Clicking another tab on the left or opening a new .prql file should switch the SQL Preview Pane to show the result of that query.
* I like the "Copy SQL to Clipboard" icon at the top
* For myself, I don't need either the "Generate SQL File" icon at the top (I don't preserve SQL results), or the "Open SQL Preview" icon (since it would always be present)
* I like the "Copied SQL to Clipboard" confirmation. It can go away automatically after ~5-10 seconds.

Thanks.

**Comment by RandomFractals** [comment]
Sql Preview has been refactored and changed to support multiple PRQL document output views, serialization, and restore on vscode reload and many other features centered around individual PRQL documents linked to the corresponding SQL Preview views rather than using a single view as before. See #60 and #108 for more info and changed behaviour.

**Comment by richb-hanover** [comment]
In the refactoring, I have lost the simplicity of earlier versions. Here's the result I would like: when I open any ".prql" file, I want to copy the SQL and paste it into my database. This means:

* The "Copy SQL to Clipboard" icon would always active active.
* The SQL Preview pane doesn't need to be open/visible. (If I want to view the SQL, I can always open the preview pane)
* All the rest of the icons (Generate SQL File, Open SQL Preview, View PRQL Setting) can remain the same

I am hopeful that this is a straightforward change. Thanks again for a terrific tool.

**Comment by RandomFractals** [comment]
@richb-hanover That is not how Copy SQL to Clipboard fucntionality was designed, and that functionality did not exist in prior version. You need an open SQL Preview to Copy generated SQL from it. You can also use Generate SQL file that opens the resulting SQL you can copy from a code editor and not commit that sql to your project repo, if you don't want to keep sql files in your project.

In any case, none of that Copy SQL or generate SQL file functionality was in the prior vscode extension v0.4.x you are referencing, and those changes were not made to remove the "simplicity" of the earlier versions. They are both new features and shortcuts added to work with PRQL in VSCode. Also, current SQL Preview works as most Previews work in other custom extensions, providing a preview for the open/active document.

You can review those changes in PR #49, #59, #118 with demo gifs if it's still not clear how that functionality works.

We moved on from PRQL code tools and it's up to @max-sixty  and other devs contributing here if they want to rollback those features and added functionality, or close this ticket with the clarifications of those features we've provided here.

**Comment by max-sixty** [comment]
Just to level-set on expectations:
- Overall the extension added a lot of features as a result of @RandomFractals 's work. I think it's much much better, I'm grateful for the contribution.
- As with any change, as we explore the space we might regress on some dimensions. That's why this sort of feedback from @richb-hanover is valuable
- I think there's space to re-introduce the existing "single generic preview pane" output that we had before, while keeping the new features
- My understanding is that @RandomFractals is working less on the extension now
- Others are welcome to contribute! That's the nature of open-source... If @RandomFractals wants to, he's of course very welcome to, but zero obligation

**Comment by richb-hanover** [comment]
@RandomFractals Thanks for this note. I didn't understand how the new model worked, so I created this ticket. I'm going to close it now, and as you suggest, create a new feature request.

I'll be interested to see your Data Notebook extension. Good luck!

**Comment by RandomFractals** [comment]
@richb-hanover great! thanks for opening new ticket for your feature request. I shared my notes on implementing it in #165.

Happy we were able to find a good middle ground solution for your use case.

Btw, I would love to share more info about new Data Notebook ext. with PRQL support , but I did not find any public social media handles you use. Even though I know @max-sixty doesn't like us sharing out of context bits here, you and others can find more info about Data Notebook ext. on twitter, where we shared a few demo gifs, etc.: https://twitter.com/search?f=live&q=(%23DataNotebooks)%20(from%3ATarasNovak)&src=typed_query
